Twitter Anaylsis - CSV Tables

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
import glob

In [6]:
#data files
#Twitter_API_Table = "csv_output/Twitter_API_Table1.csv"
#Twitter_API_Table2 = "csv_output/Twitter_API_Table2.csv"

#read files
#Twitter_API_Table  = pd.read_csv(Twitter_API_Table)
#Twitter_API_Table2 = pd.read_csv(Twitter_API_Table2)

#Add blank column to merge data
#Twitter_API_Table["Column"] = ""
#Twitter_API_Table2 ["Column"] = ""

In [7]:
csv_file_list = ['csv_output/Twitter_API_Table1.csv','csv_output/Twitter_API_Table2.csv']

list_of_dataframes = []
for filename in csv_file_list:
    list_of_dataframes.append(pd.read_csv(filename))

merged_df = pd.concat(list_of_dataframes)

merged_df.head()

,Unnamed: 0,id,author_id,lang,text,title,created_at,url,source,normalized_text,...,tag 2,tag 3,tag 4,Mentions Total,retweet count,reply count,like count,quote count,possibly_sensitive,tag 5
0,0,1453472698349326338,197257623,en,RT @FortuneMagazine: MTN is making its network...,NaN,2021-10-27T21:24:30.000Z,NaN,Twitter for Android,MTN,...,NaN,NaN,NaN,1,18,0,0,0,True,NaN
1,1,1453472665193394189,1318432664496623616,en,Amazonâ€‹.de: AMD Ryzen 9 5950X Box\nðŸ”— https://t...,AMD Ryzen 9 5950X Box,2021-10-27T21:24:22.000Z,https://t.co/q3rMN5ihRx,Twitter,NaN,...,partalert,pa_ryzen5950x,NaN,0,0,0,0,0,False,NaN
2,2,1453472656682991617,1018893163925331968,en,RT @TeamSChandna: Watch #SurbhiChandna's new #...,NaN,2021-10-27T21:24:20.000Z,NaN,Twitter Web App,Vitamin C Face Serum,...,Ad,RoseAndGold,NaN,2,29,0,0,0,False,NaN
3,3,1453472634319122433,705402063728017408,en,Gardenrooms and sheds to read your books.. #ga...,Rowlinson Easy Fix Spiked Border Roll 1.8m - P...,2021-10-27T21:24:14.000Z,https://t.co/tur73NW2bY,Twitter,NaN,...,ad,shed,NaN,0,0,0,0,0,False,NaN
4,4,1453472610553974786,3889570332,en,RT @studiosounds: #Listen to Dayne S - Moments...,Moments - EP by Dayne S,2021-10-27T21:24:09.000Z,https://t.co/NpunFEBHiR,Twitter Web App,Dayne S,...,Dance,AD,NaN,1,1,0,0,0,True,NaN

In [8]:
merged_total_df = merged_df.drop(['Unnamed: 0'], axis=1)
merged_total_df

,id,author_id,lang,text,title,created_at,url,source,normalized_text,type,...,tag 2,tag 3,tag 4,Mentions Total,retweet count,reply count,like count,quote count,possibly_sensitive,tag 5
0,1453472698349326338,197257623,en,RT @FortuneMagazine: MTN is making its network...,NaN,2021-10-27T21:24:30.000Z,NaN,Twitter for Android,MTN,Organization,...,NaN,NaN,NaN,1,18,0,0,0,True,NaN
1,1453472665193394189,1318432664496623616,en,Amazonâ€‹.de: AMD Ryzen 9 5950X Box\nðŸ”— https://t...,AMD Ryzen 9 5950X Box,2021-10-27T21:24:22.000Z,https://t.co/q3rMN5ihRx,Twitter,NaN,NaN,...,partalert,pa_ryzen5950x,NaN,0,0,0,0,0,False,NaN
2,1453472656682991617,1018893163925331968,en,RT @TeamSChandna: Watch #SurbhiChandna's new #...,NaN,2021-10-27T21:24:20.000Z,NaN,Twitter Web App,Vitamin C Face Serum,Product,...,Ad,RoseAndGold,NaN,2,29,0,0,0,False,NaN
3,1453472634319122433,705402063728017408,en,Gardenrooms and sheds to read your books.. #ga...,Rowlinson Easy Fix Spiked Border Roll 1.8m - P...,2021-10-27T21:24:14.000Z,https://t.co/tur73NW2bY,Twitter,NaN,NaN,...,ad,shed,NaN,0,0,0,0,0,False,NaN
4,1453472610553974786,3889570332,en,RT @studiosounds: #Listen to Dayne S - Moments...,Moments - EP by Dayne S,2021-10-27T21:24:09.000Z,https://t.co/NpunFEBHiR,Twitter Web App,Dayne S,Person,...,Dance,AD,NaN,1,1,0,0,0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,1453475917800607744,4846392425,en,RT @davelackie: I'm co-hosting the Beauty's Be...,NaN,2021-10-27T21:37:17.000Z,NaN,Twitter Web App,NaN,NaN,...,NaN,NaN,NaN,1,213,0,0,0,False,NaN
82,1453475885051482124,4846392425,en,RT @davelackie: Excited to be co-hosting the B...,NaN,2021-10-27T21:37:09.000Z,NaN,Twitter Web App,NaN,NaN,...,NaN,NaN,NaN,1,68,0,0,0,False,NaN
83,1453475881486192643,1122250512902934528,en,RT @falcodrin: ðŸ”¥ BESTBUY : XFX Radeon RX 6600 ...,NaN,2021-10-27T21:37:09.000Z,https://t.co/EHtgTkhpNI,Twitter for Android,XFX Radeon RX 6600 XT Speedster QICK308,Product,...,NaN,NaN,NaN,1,1,0,0,0,False,NaN
84,1453475866957139969,1349702570739183618,en,"Apple 13"" MacBook Air Silver | 1.6GHz i5 16GB ...",NaN,2021-10-27T21:37:05.000Z,https://t.co/Z4TSHkiPG6,dlvr.it,Apple 13,Product,...,refurbished,deals,NaN,0,0,0,0,0,False,NaN
85,1453475856186183681,741458105406365696,en,RT @allkpop: JEON SOMI's first debut studio al...,NaN,2021-10-27T21:37:03.000Z,NaN,Twitter for Android,JEON SOMI,Person,...,NaN,NaN,NaN,1,53,0,0,0,False,NaN

In [41]:
# mini df
mini_tags = merged_total_df[['tag 1', 'tag 2', 'tag 3', 'tag 4', 'tag 5']]

# count number of tags per tweet
mini_tags['tag counts'] = mini_tags.count(axis =1)

# merge with retweets and likes
retweets_df = merged_total_df['retweet count']
likes_df = merged_total_df['like count']

# graph number of tags against retweets and likes
mini_merged.head()

/var/folders/6j/g7z_h15n2xb6lf5plnw73lrm0000gn/T/ipykernel_54173/2921102251.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mini_tags['tag counts'] = mini_tags.count(axis =1)
/var/folders/6j/g7z_h15n2xb6lf5plnw73lrm0000gn/T/ipykernel_54173/2921102251.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retweets_df['fake'] = merged_total_df['id']

  tag 1      tag 2          tag 3 tag 4 tag 5  tag counts  retweet count
0    ad        NaN            NaN   NaN   NaN           1             18
0    ad        NaN            NaN   NaN   NaN           1            177
0    ad        NaN            NaN   NaN   NaN           1             18
0    ad        NaN            NaN   NaN   NaN           1            177
1    ad  partalert  pa_ryzen5950x   NaN   NaN           3              0

In [27]:
merged_total_df.to_csv('csv_output/Twitter_API_Merged_Table.csv')